version: "3"
services:
  overseerr:
    container_name: overseerr
    image: sctx/overseerr:1.30.1
    environment:
      - TZ=${TZ}
    volumes:
      - ${APP_DATA_DIR}/data/config:/app/config
    ports:
      - ${APP_PORT}:5055
    restart: unless-stopped
    dns:
      - ${DNS_IP}
    networks:
      - tipi_main_network
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.overseerr.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.overseerr.entrypoints: websecure
      traefik.http.routers.overseerr.service: overseerr
      traefik.http.routers.overseerr.tls.certresolver: myresolver
      traefik.http.services.overseerr.loadbalancer.server.port: 5055
