version: "3.7"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - AUTO_UPDATE=true
    dns:
      - ${DNS_IP}
    volumes:
      - ${APP_DATA_DIR}/data:/config
      - ${ROOT_FOLDER_HOST}/media/torrents:/media/torrents
    ports:
      - ${APP_PORT}:9117
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.jackett-web-redirect.redirectscheme.scheme: https
      traefik.http.services.jackett.loadbalancer.server.port: 9117
      # Web
      traefik.http.routers.jackett-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.jackett-insecure.entrypoints: web
      traefik.http.routers.jackett-insecure.service: jackett
      traefik.http.routers.jackett-insecure.middlewares: jackett-web-redirect
      # Websecure
      traefik.http.routers.jackett.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.jackett.entrypoints: websecure
      traefik.http.routers.jackett.service: jackett
      traefik.http.routers.jackett.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.jackett-local-insecure.rule: Host(`jackett.${LOCAL_DOMAIN}`)
      traefik.http.routers.jackett-local-insecure.entrypoints: web
      traefik.http.routers.jackett-local-insecure.service: jackett
      traefik.http.routers.jackett-local-insecure.middlewares: jackett-web-redirect
      # Local domain secure
      traefik.http.routers.jackett-local.rule: Host(`jackett.${LOCAL_DOMAIN}`)
      traefik.http.routers.jackett-local.entrypoints: websecure
      traefik.http.routers.jackett-local.service: jackett
      traefik.http.routers.jackett-local.tls: true
