services:
  tinyauth:
    container_name: tinyauth
    image: ghcr.io/steveiliop56/tinyauth:v3.2.1
    restart: unless-stopped
    environment:
      - SECRET=${TINYAUTH_SECRET}
      - APP_URL=${TINYAUTH_APP_URL}
      - USERS=${TINYAUTH_USERS}
      - GITHUB_CLIENT_ID=${TINYAUTH_GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${TINYAUTH_GITHUB_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${TINYAUTH_GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${TINYAUTH_GOOGLE_CLIENT_SECRET}
      - OAUTH_WHITELIST=${TINYAUTH_OAUTH_WHITELIST}
      - DISABLE_CONTINUE=${TINYAUTH_DISABLE_CONTINUE}
      - APP_TITLE=${TINYAUTH_APP_TITLE}
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.tinyauth-web-redirect.redirectscheme.scheme: https
      traefik.http.services.tinyauth.loadbalancer.server.port: 3000
      # Web
      traefik.http.routers.tinyauth-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.tinyauth-insecure.entrypoints: web
      traefik.http.routers.tinyauth-insecure.service: tinyauth
      traefik.http.routers.tinyauth-insecure.middlewares: tinyauth-web-redirect
      # Websecure
      traefik.http.routers.tinyauth.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.tinyauth.entrypoints: websecure
      traefik.http.routers.tinyauth.service: tinyauth
      traefik.http.routers.tinyauth.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.tinyauth-local-insecure.rule: Host(`tinyauth.${LOCAL_DOMAIN}`)
      traefik.http.routers.tinyauth-local-insecure.entrypoints: web
      traefik.http.routers.tinyauth-local-insecure.service: tinyauth
      traefik.http.routers.tinyauth-local-insecure.middlewares: tinyauth-web-redirect
      # Local domain secure
      traefik.http.routers.tinyauth-local.rule: Host(`tinyauth.${LOCAL_DOMAIN}`)
      traefik.http.routers.tinyauth-local.entrypoints: websecure
      traefik.http.routers.tinyauth-local.service: tinyauth
      traefik.http.routers.tinyauth-local.tls: true
      # Runtipi managed
      runtipi.managed: true
