version: '3.7'
services:
  emby:
    image: lscr.io/linuxserver/emby:4.9.3
    container_name: emby
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${ROOT_FOLDER_HOST}/media/data:/media/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    restart: unless-stopped
    ports:
      - ${APP_PORT}:8096
    networks:
      - tipi_main_network
    labels:
      traefik.enable: true
      traefik.http.middlewares.emby-web-redirect.redirectscheme.scheme: https
      traefik.http.services.emby.loadbalancer.server.port: 8096
      traefik.http.routers.emby-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.emby-insecure.entrypoints: web
      traefik.http.routers.emby-insecure.service: emby
      traefik.http.routers.emby-insecure.middlewares: emby-web-redirect
      traefik.http.routers.emby.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.emby.entrypoints: websecure
      traefik.http.routers.emby.service: emby
      traefik.http.routers.emby.tls.certresolver: myresolver
      traefik.http.routers.emby-local-insecure.rule: Host(`emby.${LOCAL_DOMAIN}`)
      traefik.http.routers.emby-local-insecure.entrypoints: web
      traefik.http.routers.emby-local-insecure.service: emby
      traefik.http.routers.emby-local-insecure.middlewares: emby-web-redirect
      traefik.http.routers.emby-local.rule: Host(`emby.${LOCAL_DOMAIN}`)
      traefik.http.routers.emby-local.entrypoints: websecure
      traefik.http.routers.emby-local.service: emby
      traefik.http.routers.emby-local.tls: true
      runtipi.managed: true
