version: "3.7"

services:
  teddit:
    image: teddit/teddit:latest
    container_name: teddit
    networks:
      - tipi_main_network
    ports:
      - ${APP_PORT}:8080
    depends_on:
      - teddit-redis
    restart: unless-stopped
    environment:
      - REDIS_HOST=teddit-redis
      - DOMAIN=${APP_DOMAIN}
      - THEME=dark
      - HTTPS_ENABLED=false
      - REDIRECT_HTTP_TO_HTTPS=false
      - REDIRECT_WWW=false
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost:8080/about"]
      interval: 1m
      timeout: 3s
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.teddit.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.teddit.entrypoints: websecure
      traefik.http.routers.teddit.service: teddit
      traefik.http.routers.teddit.tls.certresolver: myresolver
      traefik.http.services.teddit.loadbalancer.server.port: 8080
  
  teddit-redis:
    image: redis:alpine
    container_name: teddit-redis
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
