services:
  plexist:
    container_name: plexist
    image: gyarbij/plexist:latest
    environment:
      - PLEX_URL=                # your local plex url
      - PLEX_TOKEN=              # your plex token
      - WRITE_MISSING_AS_CSV=    # <1 or 0>, Default 0, 1 = writes missing tracks to a csv
      - ADD_PLAYLIST_POSTER=     # <1 or 0>, Default 1, 1 = add poster for each playlist
      - ADD_PLAYLIST_DESCRIPTION=# <1 or 0>, Default 1, 1 = add description for each playlist
      - APPEND_INSTEAD_OF_SYNC=  # <0 or 1>, Default 0, 1 = Sync tracks, 0 = Append only
      - SECONDS_TO_WAIT=84000    # Seconds to wait between syncs
      - SPOTIFY_CLIENT_ID=       # your spotify client id
      - SPOTIFY_CLIENT_SECRET=   # your spotify client secret
      - SPOTIFY_USER_ID=         # your spotify user id
      - DEEZER_USER_ID=          # your deezer user id
      - DEEZER_PLAYLIST_ID=      # deezer playlist ids space separated
    restart: unless-stopped
