version: "3.9"
services:
  radarr:
    image: ghcr.io/linuxserver/radarr:5.3.6
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    dns:
      - ${DNS_IP}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/data:/config
      - ${ROOT_FOLDER_HOST}/media:/media
    ports:
      - ${APP_PORT}:7878
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.radarr-web-redirect.redirectscheme.scheme: https
      traefik.http.services.radarr.loadbalancer.server.port: 7878
      # Web
      traefik.http.routers.radarr-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.radarr-insecure.entrypoints: web
      traefik.http.routers.radarr-insecure.service: radarr
      traefik.http.routers.radarr-insecure.middlewares: radarr-web-redirect
      # Websecure
      traefik.http.routers.radarr.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.radarr.entrypoints: websecure
      traefik.http.routers.radarr.service: radarr
      traefik.http.routers.radarr.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.radarr-local-insecure.rule: Host(`radarr.${LOCAL_DOMAIN}`)
      traefik.http.routers.radarr-local-insecure.entrypoints: web
      traefik.http.routers.radarr-local-insecure.service: radarr
      traefik.http.routers.radarr-local-insecure.middlewares: radarr-web-redirect
      # Local domain secure
      traefik.http.routers.radarr-local.rule: Host(`radarr.${LOCAL_DOMAIN}`)
      traefik.http.routers.radarr-local.entrypoints: websecure
      traefik.http.routers.radarr-local.service: radarr
      traefik.http.routers.radarr-local.tls: true
