version: "3.9"
services:
  getashell:
    image: ghcr.io/steveiliop56/getashell:v1.1.3
    container_name: getashell
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - ${APP_PORT}:3000
    networks:
      - tipi_main_network
    environment:
      - USERNAME=${GETASHELL_USERNAME}
      - PASSWORD=${GETASHELL_PASSWORD}
      - SECRET_KEY=${GETASHELL_SECRET_KEY}
    extra_hosts:
      - host.docker.internal:host-gateway
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.getashell-web-redirect.redirectscheme.scheme: https
      traefik.http.services.getashell.loadbalancer.server.port: 2368
      # Web
      traefik.http.routers.getashell-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.getashell-insecure.entrypoints: web
      traefik.http.routers.getashell-insecure.service: getashell
      traefik.http.routers.getashell-insecure.middlewares: getashell-web-redirect
      # Websecure
      traefik.http.routers.getashell.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.getashell.entrypoints: websecure
      traefik.http.routers.getashell.service: getashell
      traefik.http.routers.getashell.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.getashell-local-insecure.rule: Host(`getashell.${LOCAL_DOMAIN}`)
      traefik.http.routers.getashell-local-insecure.entrypoints: web
      traefik.http.routers.getashell-local-insecure.service: getashell
      traefik.http.routers.getashell-local-insecure.middlewares: getashell-web-redirect
      # Local domain secure
      traefik.http.routers.getashell-local.rule: Host(`getashell.${LOCAL_DOMAIN}`)
      traefik.http.routers.getashell-local.entrypoints: websecure
      traefik.http.routers.getashell-local.service: getashell
      traefik.http.routers.getashell-local.tls: true
      runtipi.managed: true
