services:
  romm:
    image: ghcr.io/rommapp/romm:3.7.3
    container_name: romm
    environment:
      - DB_HOST=romm-db
      - DB_NAME=romm
      - DB_USER=tipi
      - DB_PASSWD=${ROMM_MYSQL_PASSWORD}
      - ROMM_AUTH_SECRET_KEY=${ROMM_AUTH_SECRET_KEY}
      - IGDB_CLIENT_ID=${ROMM_IGDB_CLIENT_ID}
      - IGDB_CLIENT_SECRET=${ROMM_IGDB_CLIENT_SECRET}
      - MOBYGAMES_API_KEY=${ROMM_MOBYGAMES_API_KEY}
      - STEAMGRIDDB_API_KEY=${ROMM_STEAMGRIDDB_API_KEY}
    restart: unless-stopped
    volumes:
      - ${ROOT_FOLDER_HOST}/media/data/roms:/romm/library
      - ${APP_DATA_DIR}/data/redis:/redis-data
      - ${APP_DATA_DIR}/data/romm-resources:/romm/resources
      - ${APP_DATA_DIR}/data/config:/romm/config
      - ${APP_DATA_DIR}/data/assets:/romm/assets
    ports:
      - ${APP_PORT}:8080
    depends_on:
      - romm-db
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.romm-web-redirect.redirectscheme.scheme: https
      traefik.http.services.romm.loadbalancer.server.port: 8080
      # Web
      traefik.http.routers.romm-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.romm-insecure.entrypoints: web
      traefik.http.routers.romm-insecure.service: romm
      traefik.http.routers.romm-insecure.middlewares: romm-web-redirect
      # Websecure
      traefik.http.routers.romm.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.romm.entrypoints: websecure
      traefik.http.routers.romm.service: romm
      traefik.http.routers.romm.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.romm-local-insecure.rule: Host(`romm.${LOCAL_DOMAIN}`)
      traefik.http.routers.romm-local-insecure.entrypoints: web
      traefik.http.routers.romm-local-insecure.service: romm
      traefik.http.routers.romm-local-insecure.middlewares: romm-web-redirect
      # Local domain secure
      traefik.http.routers.romm-local.rule: Host(`romm.${LOCAL_DOMAIN}`)
      traefik.http.routers.romm-local.entrypoints: websecure
      traefik.http.routers.romm-local.service: romm
      traefik.http.routers.romm-local.tls: true
      # Runtipi managed
      runtipi.managed: true

  romm-db:
    image: lscr.io/linuxserver/mariadb:11.4.4
    container_name: romm-db
    environment:
      - MYSQL_ROOT_PASSWORD=${ROMM_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=romm
      - MYSQL_USER=tipi
      - MYSQL_PASSWORD=${ROMM_MYSQL_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/mysql/config:/config
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      # Runtipi managed
      runtipi.managed: true
