version: "3.7"
services:
  libretranslate:
    container_name: libretranslate
    image: libretranslate/libretranslate:latest
    dns:
      - ${DNS_IP}
    ports:
      - ${APP_PORT}:5000
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.libretranslate.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.libretranslate.entrypoints: websecure
      traefik.http.routers.libretranslate.service: libretranslate
      traefik.http.routers.libretranslate.tls.certresolver: myresolver
      traefik.http.services.libretranslate.loadbalancer.server.port: 5000

