version: "3.5"
services:
  dashdot:
    image: mauricenino/dashdot:5.8.0
    restart: unless-stopped
    container_name: dashdot
    privileged: true
    ports:
      - ${APP_PORT}:3001
    volumes:
      - /:/mnt/host:ro
    environment:
      - DASHDOT_SHOW_HOST=false
      - DASHDOT_SHOW_DASH_VERSION=true
      - DASHDOT_ENABLE_CPU_TEMPS=true
      - DASHDOT_USE_IMPERIAL=true
      - DASHDOT_ALWAYS_SHOW_PERCENTAGES=true
      - DASHDOT_PAGE_TITLE=dashdot
      - DASHDOT_ACCEPT_OOKLA_EULA=true
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.dashdot-web-redirect.redirectscheme.scheme: https
      traefik.http.services.dashdot.loadbalancer.server.port: 3001
      # Web
      traefik.http.routers.dashdot-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.dashdot-insecure.entrypoints: web
      traefik.http.routers.dashdot-insecure.service: dashdot
      traefik.http.routers.dashdot-insecure.middlewares: dashdot-web-redirect
      # Websecure
      traefik.http.routers.dashdot.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.dashdot.entrypoints: websecure
      traefik.http.routers.dashdot.service: dashdot
      traefik.http.routers.dashdot.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.dashdot-local-insecure.rule: Host(`dashdot.${LOCAL_DOMAIN}`)
      traefik.http.routers.dashdot-local-insecure.entrypoints: web
      traefik.http.routers.dashdot-local-insecure.service: dashdot
      traefik.http.routers.dashdot-local-insecure.middlewares: dashdot-web-redirect
      # Local domain secure
      traefik.http.routers.dashdot-local.rule: Host(`dashdot.${LOCAL_DOMAIN}`)
      traefik.http.routers.dashdot-local.entrypoints: websecure
      traefik.http.routers.dashdot-local.service: dashdot
      traefik.http.routers.dashdot-local.tls: true
