version: '3.5'
services:
  dashdot:
    image: mauricenino/dashdot:5.1.3
    restart: unless-stopped
    container_name: dashdot
    privileged: true
    ports:
      - ${APP_PORT}:3001
    volumes:
      - /:/mnt/host:ro
    environment:
      - DASHDOT_SHOW_HOST=false
      - DASHDOT_SHOW_DASH_VERSION=true
      - DASHDOT_ENABLE_CPU_TEMPS=true
      - DASHDOT_USE_IMPERIAL=true
      - DASHDOT_ALWAYS_SHOW_PERCENTAGES=true
      - DASHDOT_PAGE_TITLE=dashdot
      - DASHDOT_ACCEPT_OOKLA_EULA=true
    networks:
      - tipi_main_network
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.dashdot.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.dashdot.entrypoints: websecure
      traefik.http.routers.dashdot.service: dashdot
      traefik.http.routers.dashdot.tls.certresolver: myresolver
      traefik.http.services.dashdot.loadbalancer.server.port: 3001
