version: "3"

services:
  podfetch:
    container_name: podfetch
    image: samuel19982/podgrabv2:latest
    ports:
      - ${APP_PORT}:8000
    volumes:
      - ${APP_DATA_DIR}/data/podfetch-db:/app/db
      - ${ROOT_FOLDER_HOST}/media/data/podcasts:/app/podcasts
    environment:
      - BASIC_AUTH=true
      - USERNAME=${PODFETCH_USERNAME}
      - PASSWORD=${PODFETCH_PASSWORD}
      - POLLING_INTERVAL=60
      - SERVER_URL=https://${APP_DOMAIN}
      - PODINDEX_API_KEY=${PODFETCH_PODINDEX_API_KEY}
      - PODINDEX_API_SECRET=${PODFETCH_PODINDEX_API_SECRET}
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.podfetch.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.podfetch.entrypoints: websecure
      traefik.http.routers.podfetch.service: podfetch
      traefik.http.routers.podfetch.tls.certresolver: myresolver
      traefik.http.services.podfetch.loadbalancer.server.port: 8000

