version: '3.9'
services:
  beszel-agent:
    image: henrygd/beszel-agent:0.9.1
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - PORT=45876
      - KEY=${BESZEL_AGENT_KEY}
    labels:
      # Disable traefik
      traefik.enable: false
      # Runtipi managed
      runtipi.managed: true
