version: "3.7"
services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz:0.6.9-nbxyz2
    container_name: netbootxyz
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/assets:/assets
    ports:
      - ${APP_PORT}:3000
      - 69:69/udp
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.netbootxyz-web-redirect.redirectscheme.scheme: https
      traefik.http.services.netbootxyz.loadbalancer.server.port: 19999
      # Web
      traefik.http.routers.netbootxyz-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.netbootxyz-insecure.entrypoints: web
      traefik.http.routers.netbootxyz-insecure.service: netbootxyz
      traefik.http.routers.netbootxyz-insecure.middlewares: netbootxyz-web-redirect
      # Websecure
      traefik.http.routers.netbootxyz.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.netbootxyz.entrypoints: websecure
      traefik.http.routers.netbootxyz.service: netbootxyz
      traefik.http.routers.netbootxyz.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.netbootxyz-local-insecure.rule: Host(`netbootxyz.${LOCAL_DOMAIN}`)
      traefik.http.routers.netbootxyz-local-insecure.entrypoints: web
      traefik.http.routers.netbootxyz-local-insecure.service: netbootxyz
      traefik.http.routers.netbootxyz-local-insecure.middlewares: netbootxyz-web-redirect
      # Local domain secure
      traefik.http.routers.netbootxyz-local.rule: Host(`netbootxyz.${LOCAL_DOMAIN}`)
      traefik.http.routers.netbootxyz-local.entrypoints: websecure
      traefik.http.routers.netbootxyz-local.service: netbootxyz
      traefik.http.routers.netbootxyz-local.tls: true