version: "3.9"

services:
  email-oauth2-proxy:
    container_name: email-oauth2-proxy
    image: ghcr.io/blacktirion/email-oauth2-proxy-docker:2024.01.22
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/config:/config:rw
    environment:
      - DEBUG=true
      - CACHE_STORE=/config/credstore.config
      - LOGFILE=true
      - LOCAL_SERVER_AUTH=true
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: false