services:
  siyuan:
    image: b3log/siyuan:v3.1.20
    container_name: siyuan
    command: ['--workspace=/siyuan/workspace/', '--accessAuthCode=${SIYUAN_ACCESS_AUTH_CODE}']
    user: "1000:1000"
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/workspace:/siyuan/workspace/
    ports:
      - ${APP_PORT}:6806
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.siyuan-web-redirect.redirectscheme.scheme: https
      traefik.http.services.siyuan.loadbalancer.server.port: 6806
      # Web
      traefik.http.routers.siyuan-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.siyuan-insecure.entrypoints: web
      traefik.http.routers.siyuan-insecure.service: siyuan
      traefik.http.routers.siyuan-insecure.middlewares: siyuan-web-redirect
      # Websecure
      traefik.http.routers.siyuan.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.siyuan.entrypoints: websecure
      traefik.http.routers.siyuan.service: siyuan
      traefik.http.routers.siyuan.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.siyuan-local-insecure.rule: Host(`siyuan.${LOCAL_DOMAIN}`)
      traefik.http.routers.siyuan-local-insecure.entrypoints: web
      traefik.http.routers.siyuan-local-insecure.service: siyuan
      traefik.http.routers.siyuan-local-insecure.middlewares: siyuan-web-redirect
      # Local domain secure
      traefik.http.routers.siyuan-local.rule: Host(`siyuan.${LOCAL_DOMAIN}`)
      traefik.http.routers.siyuan-local.entrypoints: websecure
      traefik.http.routers.siyuan-local.service: siyuan
      traefik.http.routers.siyuan-local.tls: true
      runtipi.managed: true


      