services:
  nextcloud-mini:
    container_name: nextcloud-mini
    image: nextcloud:29.0.11-apache
    restart: unless-stopped
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${APP_DATA_DIR}/data/nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=nextcloud-mini-db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${NEXTCLOUD_MINI_DB_PASSWORD}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_MINI_ADMIN_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_MINI_ADMIN_USER}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_MINI_TRUSTED_DOMAINS}
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.nextcloud-mini-web-redirect.redirectscheme.scheme: https
      traefik.http.services.nextcloud-mini.loadbalancer.server.port: 80
      # Web
      traefik.http.routers.nextcloud-mini-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.nextcloud-mini-insecure.entrypoints: web
      traefik.http.routers.nextcloud-mini-insecure.service: nextcloud-mini
      traefik.http.routers.nextcloud-mini-insecure.middlewares: nextcloud-mini-web-redirect
      # Websecure
      traefik.http.routers.nextcloud-mini.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.nextcloud-mini.entrypoints: websecure
      traefik.http.routers.nextcloud-mini.service: nextcloud-mini
      traefik.http.routers.nextcloud-mini.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.nextcloud-mini-local-insecure.rule: Host(`nextcloud-mini.${LOCAL_DOMAIN}`)
      traefik.http.routers.nextcloud-mini-local-insecure.entrypoints: web
      traefik.http.routers.nextcloud-mini-local-insecure.service: nextcloud-mini
      traefik.http.routers.nextcloud-mini-local-insecure.middlewares: nextcloud-mini-web-redirect
      # Local domain secure
      traefik.http.routers.nextcloud-mini-local.rule: Host(`nextcloud-mini.${LOCAL_DOMAIN}`)
      traefik.http.routers.nextcloud-mini-local.entrypoints: websecure
      traefik.http.routers.nextcloud-mini-local.service: nextcloud-mini
      traefik.http.routers.nextcloud-mini-local.tls: true
      # Runtipi managed
      runtipi.managed: true

  nextcloud-mini-db:
    container_name: nextcloud-mini-db
    image: postgres:16
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${NEXTCLOUD_MINI_DB_PASSWORD}
    networks:
      - tipi_main_network
    labels:
      # Runtipi managed
      runtipi.managed: true
