version: "2.1"
services:
  tautulli:
    container_name: tautulli
    image: lscr.io/linuxserver/tautulli:2.10.4
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ} # Can use any env variable. List in runtipi/templates/env-sample
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    ports:
      - ${APP_PORT}:8181
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.tautulli.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.tautulli.entrypoints: websecure
      traefik.http.routers.tautulli.service: tautulli
      traefik.http.routers.tautulli.tls.certresolver: myresolver
      traefik.http.services.tautulli.loadbalancer.server.port: 8181