version: "3.7"

services:
  grampsweb:
    image: ghcr.io/gramps-project/grampsweb:v24.12.2
    container_name: grampsweb
    restart: unless-stopped
    ports:
      - ${APP_PORT}:5000 # host:docker
    environment:
      GRAMPSWEB_TREE: ${GRAMPSWEB_TREE} # will create a new tree if not exists
      GUNICORN_NUM_WORKERS: 1
    volumes:
      - ${APP_DATA_DIR}/users:/app/users # persist user database
      - ${APP_DATA_DIR}/index:/app/indexdir # persist search index
      - ${APP_DATA_DIR}/thumb_cache:/app/thumbnail_cache # persist thumbnails
      - ${APP_DATA_DIR}/cache:/app/cache # persist export and report caches
      - ${APP_DATA_DIR}/secret:/app/secret # persist flask secret
      - ${APP_DATA_DIR}/db:/root/.gramps/grampsdb # persist Gramps database
      - ${APP_DATA_DIR}/media:/app/media # persist media files
      - ${APP_DATA_DIR}/tmp:/tmp
    networks:
      - tipi_main_network
    labels:
      # Main
      runtipi.managed: true
      traefik.enable: true
      traefik.http.middlewares.grampsweb-web-redirect.redirectscheme.scheme: https
      traefik.http.services.grampsweb.loadbalancer.server.port: 80
      # Web
      traefik.http.routers.grampsweb-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.grampsweb-insecure.entrypoints: web
      traefik.http.routers.grampsweb-insecure.service: grampsweb
      traefik.http.routers.grampsweb-insecure.middlewares: grampsweb-web-redirect
      # Websecure
      traefik.http.routers.grampsweb.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.grampsweb.entrypoints: websecure
      traefik.http.routers.grampsweb.service: grampsweb
      traefik.http.routers.grampsweb.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.grampsweb-local-insecure.rule: Host(`grampsweb.${LOCAL_DOMAIN}`)
      traefik.http.routers.grampsweb-local-insecure.entrypoints: web
      traefik.http.routers.grampsweb-local-insecure.service: grampsweb
      traefik.http.routers.grampsweb-local-insecure.middlewares: grampsweb-web-redirect
      # Local domain secure
      traefik.http.routers.grampsweb-local.rule: Host(`grampsweb.${LOCAL_DOMAIN}`)
      traefik.http.routers.grampsweb-local.entrypoints: websecure
      traefik.http.routers.grampsweb-local.service: grampsweb
      traefik.http.routers.grampsweb-local.tls: true
