services:
  lubelogger:
    image: ghcr.io/hargata/lubelogger:v1.4.3
    container_name: lubelogger
    environment:
      - TZ=${TZ}
      - LOGGING__LOGLEVEL__DEFAULT=Error
      - LC_ALL=${LUBELOGGER_LOCALE:-en_US.UTF-8}
      - LANG=${LUBELOGGER_LOCALE:-en_US.UTF-8}
      - POSTGRES_CONNECTION=Host=lubelogger-db:5432;Username=tipi;Password=tipi;Database=lubelogger;
      - EnableAuth=${LUBELOGGER_ENABLE_AUTH:-false}
      - UserNameHash=${LUBELOGGER_USERNAME_HASH}
      - UserPasswordHash=${LUBELOGGER_PASSWORD_HASH}
      - LUBELOGGER_ALLOWED_FILE_EXTENSIONS=${LUBELOGGER_ALLOWED_FILE_EXTENSIONS:-*}
      - LUBELOGGER_LOGO_URL=${LUBELOGGER_CUSTOM_LOGO_URL}
      - LUBELOGGER_MOTD=${LUBELOGGER_MOTD}
      - LUBELOGGER_WEBHOOK=${LUBELOGGER_WEBHOOK_URL}
      - MailConfig__EmailServer=${LUBELOGGER_EMAIL_SERVER}
      - MailConfig__EmailFrom=${LUBELOGGER_EMAIL_FROM}
      - MailConfig__UseSSL=${LUBELOGGER_EMAIL_USE_SSL:-false}
      - MailConfig__Port=${LUBELOGGER_EMAIL_PORT:-587}
      - MailConfig__Username=${LUBELOGGER_EMAIL_USERNAME}
      - MailConfig__Password=${LUBELOGGER_EMAIL_PASSWORD}
      - OpenIDConfig__Name=${LUBELOGGER_OPENID_NAME}
      - OpenIDConfig__ClientId=${LUBELOGGER_OPENID_CLIENT_ID}
      - OpenIDConfig__ClientSecret=${LUBELOGGER_OPENID_CLIENT_SECRET}
      - OpenIDConfig__AuthURL=${LUBELOGGER_OPENID_AUTH_URL}
      - OpenIDConfig__TokenURL=${LUBELOGGER_OPENID_TOKEN_URL}
      - OpenIDConfig__RedirectURL=${LUBELOGGER_OPENID_REDIRECT_URL}
      - OpenIDConfig__Scope=${LUBELOGGER_OPENID_SCOPE}
      - OpenIDConfig__ValidateState=${LUBELOGGER_OPENID_VALIDATE_STATE:-false}
    restart: unless-stopped
    ports:
      - ${APP_PORT}:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/data/config:/App/config
      - ${APP_DATA_DIR}/data/data:/App/data
      - ${APP_DATA_DIR}/data/documents:/App/wwwroot/documents
      - ${APP_DATA_DIR}/data/images:/App/wwwroot/images
      - ${APP_DATA_DIR}/data/log:/App/log
      - ${APP_DATA_DIR}/data/keys:/root/.aspnet/DataProtection-Keys
      - ${APP_DATA_DIR}/data/temp:/App/wwwroot/temp
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.lubelogger-web-redirect.redirectscheme.scheme: https
      traefik.http.services.lubelogger.loadbalancer.server.port: 8080
      # Web
      traefik.http.routers.lubelogger-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.lubelogger-insecure.entrypoints: web
      traefik.http.routers.lubelogger-insecure.service: lubelogger
      traefik.http.routers.lubelogger-insecure.middlewares: lubelogger-web-redirect
      # Websecure
      traefik.http.routers.lubelogger.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.lubelogger.entrypoints: websecure
      traefik.http.routers.lubelogger.service: lubelogger
      traefik.http.routers.lubelogger.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.lubelogger-local-insecure.rule: Host(`lubelogger.${LOCAL_DOMAIN}`)
      traefik.http.routers.lubelogger-local-insecure.entrypoints: web
      traefik.http.routers.lubelogger-local-insecure.service: lubelogger
      traefik.http.routers.lubelogger-local-insecure.middlewares: lubelogger-web-redirect
      # Local domain secure
      traefik.http.routers.lubelogger-local.rule: Host(`lubelogger.${LOCAL_DOMAIN}`)
      traefik.http.routers.lubelogger-local.entrypoints: websecure
      traefik.http.routers.lubelogger-local.service: lubelogger
      traefik.http.routers.lubelogger-local.tls: true
      runtipi.managed: true
  lubelogger-db:
    container_name: lubelogger-db
    image: postgres:16.4-alpine
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/init/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
    environment:
      TZ: ${TZ}
      POSTGRES_DB: lubelogger
      POSTGRES_USER: tipi
      POSTGRES_PASSWORD: tipi
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true