version: '3.9'
services:
  seedsync:
    container_name: seedsync
    image: ipsingh06/seedsync:0.8.6
    user: '${SEEDSYNC_PUID:-1000}:${SEEDSYNC_PGID:-1000}'
    environment:
      - TZ=${TZ}
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${ROOT_FOLDER_HOST}/media/torrents/complete:/downloads
    ports:
      - ${APP_PORT}:8800
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.seedsync-web-redirect.redirectscheme.scheme: https
      traefik.http.services.seedsync.loadbalancer.server.port: 8800
      # Web
      traefik.http.routers.seedsync-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.seedsync-insecure.entrypoints: web
      traefik.http.routers.seedsync-insecure.service: seedsync
      traefik.http.routers.seedsync-insecure.middlewares: seedsync-web-redirect
      # Websecure
      traefik.http.routers.seedsync.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.seedsync.entrypoints: websecure
      traefik.http.routers.seedsync.service: seedsync
      traefik.http.routers.seedsync.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.seedsync-local-insecure.rule: Host(`seedsync.${LOCAL_DOMAIN}`)
      traefik.http.routers.seedsync-local-insecure.entrypoints: web
      traefik.http.routers.seedsync-local-insecure.service: seedsync
      traefik.http.routers.seedsync-local-insecure.middlewares: seedsync-web-redirect
      # Local domain secure
      traefik.http.routers.seedsync-local.rule: Host(`seedsync.${LOCAL_DOMAIN}`)
      traefik.http.routers.seedsync-local.entrypoints: websecure
      traefik.http.routers.seedsync-local.service: seedsync
      traefik.http.routers.seedsync-local.tls: true
