version: "3"

services:
  openbooks:
    container_name: openbooks
    image: evanbuss/openbooks:4.5.0
    command: "./openbooks server --dir /books --port 80 --persist --name ${OPENBOOKS_IRC_USERNAME}"
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${ROOT_FOLDER_HOST}/media/data/books/:/books
    environment:
      - BASE_PATH=/openbooks/
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.openbooks-web-redirect.redirectscheme.scheme: https
      traefik.http.services.openbooks.loadbalancer.server.port: 80
      # Web
      traefik.http.routers.openbooks-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.openbooks-insecure.entrypoints: web
      traefik.http.routers.openbooks-insecure.service: openbooks
      traefik.http.routers.openbooks-insecure.middlewares: openbooks-web-redirect
      # Websecure
      traefik.http.routers.openbooks.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.openbooks.entrypoints: websecure
      traefik.http.routers.openbooks.service: openbooks
      traefik.http.routers.openbooks.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.openbooks-local-insecure.rule: Host(`openbooks.${LOCAL_DOMAIN}`)
      traefik.http.routers.openbooks-local-insecure.entrypoints: web
      traefik.http.routers.openbooks-local-insecure.service: openbooks
      traefik.http.routers.openbooks-local-insecure.middlewares: openbooks-web-redirect
      # Local domain secure
      traefik.http.routers.openbooks-local.rule: Host(`openbooks.${LOCAL_DOMAIN}`)
      traefik.http.routers.openbooks-local.entrypoints: websecure
      traefik.http.routers.openbooks-local.service: openbooks
      traefik.http.routers.openbooks-local.tls: true
