version: '3'

services:
  openbooks:
    container_name: openbooks
    image: evanbuss/openbooks:4.5.0
    command: './openbooks server --dir /books --port 80 --persist --name ${OPENBOOKS_IRC_USERNAME}'
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${ROOT_FOLDER_HOST}/media/data/books/openbooks:/books
    environment:
      - BASE_PATH=/openbooks/
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.openbooks.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.openbooks.entrypoints: websecure
      traefik.http.routers.openbooks.service: openbooks
      traefik.http.routers.openbooks.tls.certresolver: myresolver
      traefik.http.services.openbooks.loadbalancer.server.port: 80
    networks:
      - tipi_main_network
