services:
  plausible-ce:
    container_name: plausible-ce
    image: ghcr.io/plausible/community-edition:v2.1.4
    restart: unless-stopped
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible-db
      - plausible-events-db
    ports:
      - ${APP_PORT}:8000
    environment:
      - BASE_URL=${APP_PROTOCOL:-http}://${APP_DOMAIN}
      - SECRET_KEY_BASE=${PLAUSIBLE_SECRET_KEY_BASE}
      - DATABASE_URL=postgres://tipi:${PLAUSIBLE_DB_PASSWORD}@plausible-db:5432/plausible-db
      - CLICKHOUSE_DATABASE_URL=http://plausible-events-db:8123/plausible_events_db
      - DISABLE_REGISTRATION=${PLAUSIBLE_DISABLE_REGISTRATION:-invite-only}
      - ENABLE_EMAIL_VERIFICATION=${PLAUSIBLE_ENABLE_EMAIL_VERIFICATION:-false}
      - TOTP_VAULT_KEY=${PLAUSIBLE_TOTP_VAULT_KEY}
      - GOOGLE_CLIENT_ID=${PLAUSIBLE_GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${PLAUSIBLE_GOOGLE_CLIENT_SECRET}
      - MAXMIND_LICENSE_KEY=${PLAUSIBLE_MAXMIND_LICENSE_KEY}
      - MAXMIND_EDITION=${PLAUSIBLE_MAXMIND_EDITION:-GeoLite2-City}
      - MAILER_ADAPTER=${PLAUSIBLE_MAILER_ADAPTER:-Bamboo.SMTPAdapter}
      - MAILER_EMAIL=${PLAUSIBLE_MAILER_EMAIL:-plausible@${APP_DOMAIN}}
      - MAILER_NAME=${PLAUSIBLE_MAILER_NAME:-Plausible}
      - SMTP_HOST_ADDR=${PLAUSIBLE_SMTP_HOST_ADDR}
      - SMTP_HOST_PORT=${PLAUSIBLE_SMTP_HOST_PORT}
      - SMTP_USER_NAME=${PLAUSIBLE_SMTP_USER_NAME}
      - SMTP_USER_PWD=${PLAUSIBLE_SMTP_USER_PWD}
      - SMTP_HOST_SSL_ENABLED=${PLAUSIBLE_SMTP_HOST_SSL_ENABLED:-false}
      - SMTP_RETRIES=${PLAUSIBLE_SMTP_RETRIES:-2}
      - POSTMARK_API_KEY=${PLAUSIBLE_POSTMARK_API_KEY}
      - MAILGUN_API_KEY=${PLAUSIBLE_MAILGUN_API_KEY}
      - MAILGUN_DOMAIN=${PLAUSIBLE_MAILGUN_DOMAIN}
      - MAILGUN_BASE_URI=${PLAUSIBLE_MAILGUN_BASE_URI:-https://api.mailgun.net/v3}
      - MANDRILL_API_KEY=${PLAUSIBLE_MANDRILL_API_KEY}
      - SENDGRID_API_KEY=${PLAUSIBLE_SENDGRID_API_KEY}
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.plausible-web-redirect.redirectscheme.scheme: https
      traefik.http.services.plausible.loadbalancer.server.port: 8000
      # Web
      traefik.http.routers.plausible-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.plausible-insecure.entrypoints: web
      traefik.http.routers.plausible-insecure.service: plausible
      traefik.http.routers.plausible-insecure.middlewares: plausible-web-redirect
      # Websecure
      traefik.http.routers.plausible.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.plausible.entrypoints: websecure
      traefik.http.routers.plausible.service: plausible
      traefik.http.routers.plausible.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.plausible-local-insecure.rule: Host(`plausible.${LOCAL_DOMAIN}`)
      traefik.http.routers.plausible-local-insecure.entrypoints: web
      traefik.http.routers.plausible-local-insecure.service: plausible
      traefik.http.routers.plausible-local-insecure.middlewares: plausible-web-redirect
      # Local domain secure
      traefik.http.routers.plausible-local.rule: Host(`plausible.${LOCAL_DOMAIN}`)
      traefik.http.routers.plausible-local.entrypoints: websecure
      traefik.http.routers.plausible-local.service: plausible
      traefik.http.routers.plausible-local.tls: true
      # Runtipi managed
      runtipi.managed: true

  plausible-db:
    # Plausible v2.1.1 was tested against PostgreSQL versions 15 and 16
    # https://github.com/plausible/analytics/blob/v2.1.1/.github/workflows/elixir.yml#L21-L32
    container_name: plausible-db
    image: postgres:16-alpine
    restart: unless-stopped
    networks:
      - tipi_main_network
    volumes:
      - ${APP_DATA_DIR}/data/database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PLAUSIBLE_DB_PASSWORD}
      - POSTGRES_USER=tipi
      - POSTGRES_DB=plausible-db
    labels:
      # Runtipi managed
      runtipi.managed: true

  plausible-events-db:
    container_name: plausible-events-db
    image: clickhouse/clickhouse-server:24.3.3.102-alpine
    restart: unless-stopped
    networks:
      - tipi_main_network
    volumes:
      - ${APP_DATA_DIR}/data/event-data:/var/lib/clickhouse
      - ${APP_DATA_DIR}/data/event-logs:/var/log/clickhouse-server
      - ${APP_DATA_DIR}/data/clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ${APP_DATA_DIR}/data/clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    labels:
      # Runtipi managed
      runtipi.managed: true
