version: "3.9"
services:
  pingvin-share:
    container_name: pingvin-share
    image: stonith404/pingvin-share:v1.8.2
    restart: unless-stopped
    ports:
      - ${APP_PORT}:3000
    volumes:
      - ${APP_DATA_DIR}/data:/opt/app/backend/data
      - ${APP_DATA_DIR}/data/images:/opt/app/frontend/public/img
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.pingvin-share-web-redirect.redirectscheme.scheme: https
      traefik.http.services.pingvin-share.loadbalancer.server.port: 3000
      # Web
      traefik.http.routers.pingvin-share-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.pingvin-share-insecure.entrypoints: web
      traefik.http.routers.pingvin-share-insecure.service: pingvin-share
      traefik.http.routers.pingvin-share-insecure.middlewares: pingvin-share-web-redirect
      # Websecure
      traefik.http.routers.pingvin-share.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.pingvin-share.entrypoints: websecure
      traefik.http.routers.pingvin-share.service: pingvin-share
      traefik.http.routers.pingvin-share.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.pingvin-share-local-insecure.rule: Host(`pingvin-share.${LOCAL_DOMAIN}`)
      traefik.http.routers.pingvin-share-local-insecure.entrypoints: web
      traefik.http.routers.pingvin-share-local-insecure.service: pingvin-share
      traefik.http.routers.pingvin-share-local-insecure.middlewares: pingvin-share-web-redirect
      # Local domain secure
      traefik.http.routers.pingvin-share-local.rule: Host(`pingvin-share.${LOCAL_DOMAIN}`)
      traefik.http.routers.pingvin-share-local.entrypoints: websecure
      traefik.http.routers.pingvin-share-local.service: pingvin-share
      traefik.http.routers.pingvin-share-local.tls: true
      # Runtipi managed
      runtipi.managed: true