services:
  homer:
    image: b4bz/homer:v24.12.1
    container_name: homer
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/www/assets
    ports:
      - ${APP_PORT}:8080
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.homer-web-redirect.redirectscheme.scheme: https
      traefik.http.services.homer.loadbalancer.server.port: 8080
      # Web
      traefik.http.routers.homer-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.homer-insecure.entrypoints: web
      traefik.http.routers.homer-insecure.service: homer
      traefik.http.routers.homer-insecure.middlewares: homer-web-redirect
      # Websecure
      traefik.http.routers.homer.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.homer.entrypoints: websecure
      traefik.http.routers.homer.service: homer
      traefik.http.routers.homer.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.homer-local-insecure.rule: Host(`homer.${LOCAL_DOMAIN}`)
      traefik.http.routers.homer-local-insecure.entrypoints: web
      traefik.http.routers.homer-local-insecure.service: homer
      traefik.http.routers.homer-local-insecure.middlewares: homer-web-redirect
      # Local domain secure
      traefik.http.routers.homer-local.rule: Host(`homer.${LOCAL_DOMAIN}`)
      traefik.http.routers.homer-local.entrypoints: websecure
      traefik.http.routers.homer-local.service: homer
      traefik.http.routers.homer-local.tls: true
      # Runtipi managed
      runtipi.managed: true
