version: "3.7"

services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:1.20.0
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${APP_DATA_DIR}/data/freshrss:/config
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.freshrss.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.freshrss.entrypoints: websecure
      traefik.http.routers.freshrss.service: freshrss
      traefik.http.routers.freshrss.tls.certresolver: myresolver
      traefik.http.services.freshrss.loadbalancer.server.port: 80

    # labels:
    #     traefik.enable: true
    #     traefik.http.routers.freshrss.rule: Host(`freshrss.tipi.home`)
    #     traefik.http.routers.freshrss.service: freshrss
    #     traefik.http.routers.freshrss.tls: true
    #     traefik.http.routers.freshrss.entrypoints: websecure
    #     traefik.http.services.freshrss.loadbalancer.server.port: 80
